### ISSUE TITLE
InvalidArgumentError

### ISSUE THREAD

**Issue by kdkyum** [Blest215/MLproject_RumorDetection#3]
```
> 2017-05-28 21:46:32.967265: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Name: <unknown>, Feature: file_path (data type: string) is required but could not be found.
> INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Name: <unknown>, Feature: file_path (data type: string) is required but could not be found.
> 	 [[Node: input/ParseSingleExample/ParseExample/ParseExample = ParseExample[Ndense=5, Nsparse=0, Tdense=[DT_STRING, DT_INT64, DT_INT64, DT_STRING, DT_INT64], dense_shapes=[[], [], [], [], []], sparse_types=[], _device="/job:localhost/replica:0/task:0/cpu:0"](input/ParseSingleExample/ExpandDims, input/ParseSingleExample/ParseExample/ParseExample/names, input/ParseSingleExample/ParseExample/ParseExample/dense_keys_0, input/ParseSingleExample/ParseExample/ParseExample/dense_keys_1, input/ParseSingleExample/ParseExample/ParseExample/dense_keys_2, input/ParseSingleExample/ParseExample/ParseExample/dense_keys_3, input/ParseSingleExample/ParseExample/ParseExample/dense_keys_4, input/ParseSingleExample/ParseExample/Const, input/ParseSingleExample/ParseExample/Const_1, input/ParseSingleExample/ParseExample/Const_2, input/ParseSingleExample/ParseExample/Const_3, input/ParseSingleExample/ParseExample/Const_4)]]
> 	 [[Node: input/ParseSingleExample/ParseExample/ParseExample/_15 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_29_input/ParseSingleExample/ParseExample/ParseExample", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
> INFO 2017-05-28 21:46:32,967 tf_logging:82 info Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Name: <unknown>, Feature: file_path (data type: string) is required but could not be found.
> 	 [[Node: input/ParseSingleExample/ParseExample/ParseExample = ParseExample[Ndense=5, Nsparse=0, Tdense=[DT_STRING, DT_INT64, DT_INT64, DT_STRING, DT_INT64], dense_shapes=[[], [], [], [], []], sparse_types=[], _device="/job:localhost/replica:0/task:0/cpu:0"](input/ParseSingleExample/ExpandDims, input/ParseSingleExample/ParseExample/ParseExample/names, input/ParseSingleExample/ParseExample/ParseExample/dense_keys_0, input/ParseSingleExample/ParseExample/ParseExample/dense_keys_1, input/ParseSingleExample/ParseExample/ParseExample/dense_keys_2, input/ParseSingleExample/ParseExample/ParseExample/dense_keys_3, input/ParseSingleExample/ParseExample/ParseExample/dense_keys_4, input/ParseSingleExample/ParseExample/Const, input/ParseSingleExample/ParseExample/Const_1, input/ParseSingleExample/ParseExample/Const_2, input/ParseSingleExample/ParseExample/Const_3, input/ParseSingleExample/ParseExample/Const_4)]]
> 	 [[Node: input/ParseSingleExample/ParseExample/ParseExample/_15 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_29_input/ParseSingleExample/ParseExample/ParseExample", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
> INFO 2017-05-28 21:46:33,281 rumor_rnn:240 main 37
> Traceback (most recent call last):
>   File "rumor_rnn.py", line 278, in <module>
>     tf.app.run()
>   File "/home/kdkyum/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
>     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
>   File "rumor_rnn.py", line 249, in main
>     coord.join(threads)
>   File "/home/kdkyum/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
>     six.reraise(*self._exc_info_to_raise)
>   File "/home/kdkyum/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 237, in _run
>     enqueue_callable()
>   File "/home/kdkyum/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1063, in _single_operation_run
>     target_list_as_strings, status, None)
>   File "/home/kdkyum/anaconda2/envs/tensorflow/lib/python2.7/contextlib.py", line 24, in __exit__
>     self.gen.next()
>   File "/home/kdkyum/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
>     pywrap_tensorflow.TF_GetCode(status))
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Name: <unknown>, Feature: file_path (data type: string) is required but could not be found.
> 	 [[Node: input/ParseSingleExample/ParseExample/ParseExample = ParseExample[Ndense=5, Nsparse=0, Tdense=[DT_STRING, DT_INT64, DT_INT64, DT_STRING, DT_INT64], dense_shapes=[[], [], [], [], []], sparse_types=[], _device="/job:localhost/replica:0/task:0/cpu:0"](input/ParseSingleExample/ExpandDims, input/ParseSingleExample/ParseExample/ParseExample/names, input/ParseSingleExample/ParseExample/ParseExample/dense_keys_0, input/ParseSingleExample/ParseExample/ParseExample/dense_keys_1, input/ParseSingleExample/ParseExample/ParseExample/dense_keys_2, input/ParseSingleExample/ParseExample/ParseExample/dense_keys_3, input/ParseSingleExample/ParseExample/ParseExample/dense_keys_4, input/ParseSingleExample/ParseExample/Const, input/ParseSingleExample/ParseExample/Const_1, input/ParseSingleExample/ParseExample/Const_2, input/ParseSingleExample/ParseExample/Const_3, input/ParseSingleExample/ParseExample/Const_4)]]
> 	 [[Node: input/ParseSingleExample/ParseExample/ParseExample/_15 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_29_input/ParseSingleExample/ParseExample/ParseExample", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
```

InvalidArgumentError 원인을 못찾고 있어서 도움을 구합니다. tfrecord 파일을 차례대로 읽을 때 특정 데이터에 feature가 없다는거 같은데 tfrecord에 문제가 있는건가요.

**Comment by shygiants** [comment]
file_path라는 feature를 못찾는 거 같네요
파일에 문제가 있을 수도 있구요
읽는 부분에서 문제가 있을 수도 있어요
